/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SensorMessage'
 * message type.
 */

public class SensorMessage extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new SensorMessage of size 12. */
    public SensorMessage() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SensorMessage of the given data_length. */
    public SensorMessage(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage with the given data_length
     * and base offset.
     */
    public SensorMessage(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage using the given byte array
     * as backing store.
     */
    public SensorMessage(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage using the given byte array
     * as backing store, with the given base offset.
     */
    public SensorMessage(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SensorMessage(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage embedded in the given message
     * at the given base offset.
     */
    public SensorMessage(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMessage embedded in the given message
     * at the given base offset and length.
     */
    public SensorMessage(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SensorMessage> \n";
      try {
        s += "  [address=0x"+Long.toHexString(get_address())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [humidity=0x"+Long.toHexString(get_humidity())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temperature=0x"+Long.toHexString(get_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [solarRadiation=0x"+Long.toHexString(get_solarRadiation())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [photoRadiation=0x"+Long.toHexString(get_photoRadiation())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [voltage=0x"+Long.toHexString(get_voltage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: address
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'address' is signed (false).
     */
    public static boolean isSigned_address() {
        return false;
    }

    /**
     * Return whether the field 'address' is an array (false).
     */
    public static boolean isArray_address() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'address'
     */
    public static int offset_address() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'address'
     */
    public static int offsetBits_address() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'address'
     */
    public int get_address() {
        return (int)getUIntBEElement(offsetBits_address(), 16);
    }

    /**
     * Set the value of the field 'address'
     */
    public void set_address(int value) {
        setUIntBEElement(offsetBits_address(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'address'
     */
    public static int size_address() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'address'
     */
    public static int sizeBits_address() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: humidity
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'humidity' is signed (false).
     */
    public static boolean isSigned_humidity() {
        return false;
    }

    /**
     * Return whether the field 'humidity' is an array (false).
     */
    public static boolean isArray_humidity() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'humidity'
     */
    public static int offset_humidity() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'humidity'
     */
    public static int offsetBits_humidity() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'humidity'
     */
    public int get_humidity() {
        return (int)getUIntBEElement(offsetBits_humidity(), 16);
    }

    /**
     * Set the value of the field 'humidity'
     */
    public void set_humidity(int value) {
        setUIntBEElement(offsetBits_humidity(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'humidity'
     */
    public static int size_humidity() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'humidity'
     */
    public static int sizeBits_humidity() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (false).
     */
    public static boolean isArray_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'temperature'
     */
    public int get_temperature() {
        return (int)getUIntBEElement(offsetBits_temperature(), 16);
    }

    /**
     * Set the value of the field 'temperature'
     */
    public void set_temperature(int value) {
        setUIntBEElement(offsetBits_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'temperature'
     */
    public static int size_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temperature'
     */
    public static int sizeBits_temperature() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: solarRadiation
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'solarRadiation' is signed (false).
     */
    public static boolean isSigned_solarRadiation() {
        return false;
    }

    /**
     * Return whether the field 'solarRadiation' is an array (false).
     */
    public static boolean isArray_solarRadiation() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'solarRadiation'
     */
    public static int offset_solarRadiation() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'solarRadiation'
     */
    public static int offsetBits_solarRadiation() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'solarRadiation'
     */
    public int get_solarRadiation() {
        return (int)getUIntBEElement(offsetBits_solarRadiation(), 16);
    }

    /**
     * Set the value of the field 'solarRadiation'
     */
    public void set_solarRadiation(int value) {
        setUIntBEElement(offsetBits_solarRadiation(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'solarRadiation'
     */
    public static int size_solarRadiation() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'solarRadiation'
     */
    public static int sizeBits_solarRadiation() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: photoRadiation
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'photoRadiation' is signed (false).
     */
    public static boolean isSigned_photoRadiation() {
        return false;
    }

    /**
     * Return whether the field 'photoRadiation' is an array (false).
     */
    public static boolean isArray_photoRadiation() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'photoRadiation'
     */
    public static int offset_photoRadiation() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'photoRadiation'
     */
    public static int offsetBits_photoRadiation() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'photoRadiation'
     */
    public int get_photoRadiation() {
        return (int)getUIntBEElement(offsetBits_photoRadiation(), 16);
    }

    /**
     * Set the value of the field 'photoRadiation'
     */
    public void set_photoRadiation(int value) {
        setUIntBEElement(offsetBits_photoRadiation(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'photoRadiation'
     */
    public static int size_photoRadiation() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'photoRadiation'
     */
    public static int sizeBits_photoRadiation() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: voltage
    //   Field type: int, unsigned
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'voltage' is signed (false).
     */
    public static boolean isSigned_voltage() {
        return false;
    }

    /**
     * Return whether the field 'voltage' is an array (false).
     */
    public static boolean isArray_voltage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'voltage'
     */
    public static int offset_voltage() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'voltage'
     */
    public static int offsetBits_voltage() {
        return 80;
    }

    /**
     * Return the value (as a int) of the field 'voltage'
     */
    public int get_voltage() {
        return (int)getUIntBEElement(offsetBits_voltage(), 16);
    }

    /**
     * Set the value of the field 'voltage'
     */
    public void set_voltage(int value) {
        setUIntBEElement(offsetBits_voltage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'voltage'
     */
    public static int size_voltage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'voltage'
     */
    public static int sizeBits_voltage() {
        return 16;
    }

}
